title: Machine Learning is Fun
author: akram-mohammed 
email: akrammohd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Its awesome.

# social links
twitter_username: akram9
github_username:  akram-mohammed

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
